[tool.poetry]
name = "dangerzone"
version = "0.1.1.dev1"
description = "Take potentially dangerous PDFs, office documents, or images and convert them to a safe PDF"
authors = ["Micah Lee <micah.lee@theintercept.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
PyQt5 = "^5.14.1"
click = "^7.0"
appdirs = "^1.4.3"
requests = "^2.22.0"
pyxdg = {version = "^0.26", platform = "linux"}
pyobjc-core = {version = "^6.1", platform = "darwin"}
pyobjc-framework-launchservices = {version = "^6.1", platform = "darwin"}
macholib = "^1.14"
pywin32 = {version = "^227", platform = "windows"}
wmi = {version = "^1.4.9", platform = "windows"}

[tool.poetry.dev-dependencies]
black = "^19.10b0"
pyinstaller = {version = "^3.6", platform = "darwin"}
setuptools = {version = "^45.2.0", platform = "windows"}

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
