[tool.poetry]
name = "dangerzone"
version = "0.1.3"
description = "Take potentially dangerous PDFs, office documents, or images and convert them to a safe PDF"
authors = ["Micah Lee <micah.lee@theintercept.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.7,<3.10"
click = "^7.0"
appdirs = "^1.4.3"
requests = "^2.22.0"
macholib = "^1.14"
termcolor = "^1.1.0"
PySide2 = "^5.15.1"
pywin32 = {version = "^227", platform = "windows"}
wmi = {version = "^1.4.9", platform = "windows"}
pyxdg = {version = "^0.26", platform = "linux"}
pyobjc-core = {version = "^6.1", platform = "darwin"}
pyobjc-framework-launchservices = {version = "^6.1", platform = "darwin"}

[tool.poetry.dev-dependencies]
pyinstaller = {version = "^3.6", platform = "darwin"}
setuptools = {version = "^45.2.0", platform = "windows"}

[tool.poetry.scripts]
dangerzone = 'dangerzone:main'

[build-system]
requires = ["poetry>=1.1.4"]
build-backend = "poetry.masonry.api"
